### ISSUE TITLE
mysql database  charset

### ISSUE THREAD

**Issue by Leevampire** [wesen1/LuaORM#4]
mysql database  charset is  utf-8 , write into database,the chinese was garbled.but select the chinese data is right

**Comment by wesen1** [comment]
It looks like `SET NAMES utf8;` must be executed once after the database connection was initialized.
[https://stackoverflow.com/questions/2159434/set-names-utf8-in-mysql](https://stackoverflow.com/questions/2159434/set-names-utf8-in-mysql)

I modified the file `src/LuaORM/DatabaseConnection/LuaSQL/LuaSQLConnection` as follows, if installed via luarocks the file should be located at `/usr/local/share/lua/5.1/LuaORM/LuaORM/DatabaseConnection/LuaSQL/LuaSQLConnection.lua`.

```lua
function LuaSQLConnection:initializeConnection()

  self.environment = self:getEnvironment()

  self.connection = self:getConnection()
  if (not self.connection) then
    error("Could not connect to the database")
  end

  -- The line below was added
  self:executeQuery("SET NAMES utf8")

end
```

After adding this line chinese characters were displayed correctly in my database GUI tool.

Could you check if the problem is resolved with this line?

**Comment by Leevampire** [comment]
thanks,is ok now
